### PR TITLE
Polished docs

### PR DESCRIPTION
**Pull request by petrparolek**
- use 4 spaces in CSS, in JS, in HTML and in Latte
- use tab in NEON and in PHP
- neon highlighting syntax
- normalized filename of Readmes
- typos

### CODE REVIEW

**Comment by dakorpar** [comment]
@petrparolek What good would that bring? I don't see any real change before and after... You doing some bot for this or?

**Comment by petrparolek** [comment]
I synced by all contributte packages

**Comment by dakorpar** [comment]
description provided does not reflect changes and changes do not do anything visible for anyone.

**Comment by f3l1x** [comment]
Description is weird but changes are good and related. Why did you close it? Correct highlighting is neon.

**Comment by petrparolek** [comment]
@f3l1x could you merge it?

**Comment by dakorpar** [comment]
@petrparolek rebase it into 1 commit and I'll merge it.

**Comment by petrparolek** [comment]
done

**Pull request merged**
